name: 构建镜像推送

on:
  push:
    paths:
      - '**/Dockerfile'
      - '**/entrypoint.sh'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置镜像名称和标签
      id: set-image-name-tag
      run: |
        FILE_PATH=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -E 'Dockerfile|entrypoint.sh' | head -n 1)
        IMAGE_NAME=$(basename $(dirname $(dirname $FILE_PATH)))
        IMAGE_TAG=$(basename $(dirname $FILE_PATH))
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

    - name: 构建镜像
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

    - name: 推送到 GitHub 容器注册表
      env:
        GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
        GHCR_KEY: ${{ secrets.GHCR_KEY }}
      run: |
        echo "${GHCR_KEY}" | docker login ghcr.io -u "${GHCR_USERNAME}" --password-stdin
        GHCR_IMAGE_TAG="ghcr.io/${GHCR_USERNAME}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        docker tag "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" "${GHCR_IMAGE_TAG}"
        docker push "${GHCR_IMAGE_TAG}"

    - name: 推送到 Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
      run: |
        echo "${DOCKER_PASSWD}" | docker login docker.io -u "${DOCKER_USERNAME}" --password-stdin
        DOCKER_IMAGE_TAG="docker.io/${DOCKER_USERNAME}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        docker tag "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" "${DOCKER_IMAGE_TAG}"
        docker push "${DOCKER_IMAGE_TAG}"

    - name: 推送到阿里云容器镜像服务
      env:
        ALICLOUD_USERNAME: ${{ secrets.ALICLOUD_USERNAME }}
        ALICLOUD_PASSWORD: ${{ secrets.ALICLOUD_PASSWORD }}
        ALICLOUD_REGISTRY: ${{ secrets.ALICLOUD_REGISTRY }}
        ALICLOUD_NAMESPACE: ${{ secrets.ALICLOUD_NAMESPACE }}
      run: |
        echo "${ALICLOUD_PASSWORD}" | docker login "${ALICLOUD_REGISTRY}" -u "${ALICLOUD_USERNAME}" --password-stdin
        ALICLOUD_IMAGE_TAG="${ALICLOUD_REGISTRY}/${ALICLOUD_NAMESPACE}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        docker tag "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" "${ALICLOUD_IMAGE_TAG}"
        docker push "${ALICLOUD_IMAGE_TAG}"
